# Helpers for collecting, inspecting, serving, and cleaning CPU and memory
# profiles from Go benchmarks.
#
# This file is intended to be included by another Makefile. All variables use
# the GO_PROFILE_ prefix to avoid collisions with variables defined by the
# including project.
#
# The including Makefile should define its default target before including this
# file, or set .DEFAULT_GOAL explicitly, so one of the profiling targets does
# not accidentally become the default target.
#
# Collect and inspect a CPU profile:
#
#   make profile-cpu
#
# Collect and inspect a memory-allocation profile:
#
#   make profile-mem
#
# Open the existing CPU profile in the interactive pprof web interface:
#
#   make profile-web
#
# Remove generated profiles and compiled benchmark binaries:
#
#   make clean-profile
#
# Select another benchmark and run it for a fixed number of iterations:
#
#   make profile-cpu                         \
#       GO_PROFILE_BENCH='^BenchmarkDecode$' \
#       GO_PROFILE_BENCH_TIME=1000x
#
# Store the generated profiling files in another directory:
#
#   make profile-mem GO_PROFILE_DIR=build/profiles
#
# Run the pprof web interface on another address:
#
#   make profile-web GO_PROFILE_HTTP_ADDR=localhost:9090

# Directory used for profiling data and compiled benchmark binaries.
GO_PROFILE_DIR ?= .pprof

# Regular expression passed to go test -bench to select benchmarks.
GO_PROFILE_BENCH ?= ^BenchmarkEncode$

# Duration or fixed iteration count passed to go test -benchtime.
#
# Examples:
#
#   GO_PROFILE_BENCH_TIME=5s
#   GO_PROFILE_BENCH_TIME=1000x
GO_PROFILE_BENCH_TIME ?= 100x

# Path of the CPU profile generated by go test -cpuprofile.
GO_PROFILE_CPU ?= $(GO_PROFILE_DIR)/cpu.out

# Path of the compiled benchmark binary used to inspect the CPU profile.
GO_PROFILE_CPU_BINARY ?= $(GO_PROFILE_DIR)/cpu.test

# Path of the memory profile generated by go test -memprofile.
GO_PROFILE_MEM ?= $(GO_PROFILE_DIR)/mem.out

# Path of the compiled benchmark binary used to inspect the memory profile.
GO_PROFILE_MEM_BINARY ?= $(GO_PROFILE_DIR)/mem.test

# Address on which pprof serves its interactive web interface.
#
# Use an explicit non-loopback address to make the interface available from
# another machine:
#
#   make profile-web GO_PROFILE_HTTP_ADDR=0.0.0.0:8080
GO_PROFILE_HTTP_ADDR ?= localhost:8080

.PHONY: profile-cpu
# Collect a CPU profile and display the 15 functions responsible for the
# largest share of sampled CPU time.
profile-cpu:
	mkdir -p "$(dir $(GO_PROFILE_CPU))"         \
		"$(dir $(GO_PROFILE_CPU_BINARY))"
	go test -bench '$(GO_PROFILE_BENCH)'        \
		-benchtime=$(GO_PROFILE_BENCH_TIME) \
		-cpuprofile="$(GO_PROFILE_CPU)"     \
		-o "$(GO_PROFILE_CPU_BINARY)"
	go tool pprof -top -nodecount=15            \
		"$(GO_PROFILE_CPU_BINARY)"          \
		"$(GO_PROFILE_CPU)"

.PHONY: profile-mem
# Collect a memory profile and display the 15 functions responsible for the
# largest total amount of allocated memory.
profile-mem:
	mkdir -p "$(dir $(GO_PROFILE_MEM))"                        \
		"$(dir $(GO_PROFILE_MEM_BINARY))"
	go test -bench '$(GO_PROFILE_BENCH)'                       \
		-benchtime=$(GO_PROFILE_BENCH_TIME)                \
		-memprofile="$(GO_PROFILE_MEM)"                    \
		-o "$(GO_PROFILE_MEM_BINARY)"
	go tool pprof -top -nodecount=15 -sample_index=alloc_space \
		"$(GO_PROFILE_MEM_BINARY)"                         \
		"$(GO_PROFILE_MEM)"

.PHONY: profile-web
# Serve an interactive web interface for the existing CPU profile.
#
# Run profile-cpu first if the profile and benchmark binary do not exist:
#
#   make profile-cpu
#   make profile-web
profile-web:
	go tool pprof -http="$(GO_PROFILE_HTTP_ADDR)" \
		"$(GO_PROFILE_CPU_BINARY)"            \
		"$(GO_PROFILE_CPU)"

.PHONY: clean-profile
# Remove all profiling data and compiled benchmark binaries stored in
# GO_PROFILE_DIR.
clean-profile:
	@if [ -z "$(strip $(GO_PROFILE_DIR))" ] ||                                   \
	    [ "$(abspath $(GO_PROFILE_DIR))" = "/" ]; then                           \
		echo "refusing to remove an empty directory or the filesystem root"; \
		exit 1;                                                              \
	fi
	$(RM) -r -- "$(GO_PROFILE_DIR)"
